ARG registry
FROM $registry/labtainer.base2

ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh

RUN apt-get update && apt-get install -y apache2 supervisor inotify-tools nano php ssh openssh-server

ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /

RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo

USER $user_name
ENV HOME /home/$user_name
ADD $labdir/$imagedir/home_tar/home.tar $HOME

RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME

RUN chmod +x $HOME/entrypoint.sh

RUN chmod +x $HOME/watch_file.sh

USER root
ENTRYPOINT ["/home/student/entrypoint.sh"]
